In [1]:

import numpy as np
arr = np.array([1, 2, 3, 6, 4, 5])
print(arr[::-1])


[5 4 6 3 2 1]


In [2]:

array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])
print(array1.flatten())
print(array1.ravel())


[1 2 3 2 4 5 1 2 3]
[1 2 3 2 4 5 1 2 3]


In [3]:

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])
print(np.array_equal(arr1, arr2))


True


In [4]:

x = np.array([1,2,3,4,5,1,2,1,1,1])
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
vals, counts = np.unique(x, return_counts=True)
print(vals[np.argmax(counts)])
print(np.where(x == vals[np.argmax(counts)]))
vals, counts = np.unique(y, return_counts=True)
print(vals[np.argmax(counts)])
print(np.where(y == vals[np.argmax(counts)]))


1
(array([0, 5, 7, 8, 9]),)
1
(array([0, 1, 2]),)


In [5]:

gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
print(gfg.sum())
print(gfg.sum(axis=1))
print(gfg.sum(axis=0))


45
[[14]
 [16]
 [15]]
[[20  9 16]]


In [6]:

n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]])
print(np.trace(n_array))
w, v = np.linalg.eig(n_array)
print(w)
print(v)
print(np.linalg.inv(n_array))
print(np.linalg.det(n_array))


176
[98.16835147 28.097044   49.73460452]
[[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]
[[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
137180.0000000001


In [14]:

p1 = np.array([[1, 2], [2, 3]])
q1 = np.array([[4, 5], [6, 7]])
print(np.dot(p1, q1))
print(np.cov(p1, q1))

p2 = np.array([[1, 2], [2, 3], [4, 5]])
q2 = np.array([[4, 5, 1], [6, 7, 2]])

print(np.dot(p2, q2))
print(np.cov(p2.T, q2))  # Transpose p2 so rows match for covariance



[[16 19]
 [26 31]]
[[0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]]
[[16 19  5]
 [26 31  8]
 [46 55 14]]
[[ 2.33333333  2.33333333 -2.66666667 -3.5       ]
 [ 2.33333333  2.33333333 -2.66666667 -3.5       ]
 [-2.66666667 -2.66666667  4.33333333  5.5       ]
 [-3.5        -3.5         5.5         7.        ]]


In [8]:

x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])
print(np.inner(x, y))
print(np.outer(x, y))
print(np.tensordot(x, y, axes=0))


[[17 52]
 [13 62]]
[[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]
[[[[ 2 10  0]
   [10 20  6]]

  [[ 3 15  0]
   [15 30  9]]

  [[ 4 20  0]
   [20 40 12]]]


 [[[ 3 15  0]
   [15 30  9]]

  [[ 2 10  0]
   [10 20  6]]

  [[ 9 45  0]
   [45 90 27]]]]


In [9]:

array = np.array([[1, -2, 3],[-4, 5, -6]])
print(np.abs(array))
print(np.percentile(array, [25, 50, 75]))
print(np.percentile(array, [25, 50, 75], axis=0))
print(np.percentile(array, [25, 50, 75], axis=1))
print(np.mean(array))
print(np.median(array))
print(np.std(array))
print(np.mean(array, axis=0))
print(np.median(array, axis=0))
print(np.std(array, axis=0))
print(np.mean(array, axis=1))
print(np.median(array, axis=1))
print(np.std(array, axis=1))


[[1 2 3]
 [4 5 6]]
[-3.5 -0.5  2.5]
[[-2.75 -0.25 -3.75]
 [-1.5   1.5  -1.5 ]
 [-0.25  3.25  0.75]]
[[-0.5 -5. ]
 [ 1.  -4. ]
 [ 2.   0.5]]
-0.5
-0.5
3.8622100754188224
[-1.5  1.5 -1.5]
[-1.5  1.5 -1.5]
[2.5 3.5 4.5]
[ 0.66666667 -1.66666667]
[ 1. -4.]
[2.05480467 4.78423336]


In [10]:

a = np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0])
print(np.floor(a))
print(np.ceil(a))
print(np.trunc(a))
print(np.round(a))


[-2. -2. -1.  0.  1.  1.  3.]
[-1. -1. -0.  1.  2.  2.  3.]
[-1. -1. -0.  0.  1.  1.  3.]
[-2. -2. -0.  0.  2.  2.  3.]


In [11]:

array = np.array([10, 52, 62, 16, 16, 54, 453])
print(np.sort(array))
print(np.argsort(array))
print(np.sort(array)[:4])
print(np.sort(array)[-5:])


[ 10  16  16  52  54  62 453]
[0 3 4 1 5 2 6]
[10 16 16 52]
[ 16  52  54  62 453]


In [12]:

array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])
ints = array[array == array.astype(int)]
floats = array[array != array.astype(int)]
print(ints)
print(floats)


[1. 2. 3. 2.]
[1.2 2.2]


In [13]:

from PIL import Image

def img_to_array(path):
    img = Image.open(path)
    arr = np.array(img)
    if len(arr.shape) == 2:
        np.savetxt("image_grey.txt", arr, fmt='%d')
    else:
        np.savetxt("image_rgb.txt", arr.reshape(-1, arr.shape[-1]), fmt='%d')
    return arr

# Example: arr = img_to_array('your_image_path.jpg')
# Loaded_data = np.loadtxt("image_grey.txt")
